#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login

# config/routes.yaml
app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
# config/routes.yaml
app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
